import CardEarlyOutReminder from "../(page)/home/dashboard/CardEarlyOutReminder";

const appString = {
    authTitle: 'Welcome to',
    appNameFull: 'Teqheal Solution',
    appName1: 'Teqheal',
    appName2: 'Solution',
    empSystem: 'Employee Management System',
    authDes: 'Connecting People. Optimizing Process. Enhancing Performance.',
    authCoreValue: 'Core Values',
    coreV1: 'Working Everyday Towards Perfection',
    coreV2: 'Grow Consistently Every Day',
    coreV3: 'Inspiring Teams To Build The Best',
    coreV4: 'Creating Value Adding Services',
    signUpTitle: 'Create New Account',
    signUpDes: 'Let\'s register and connect with your co-workers to get the things done together and faster.',
    signInTitle: 'Sign In Your Account',
    signInDes: 'Welcome Back! Please Sign In to access product.',
    alreadyAcc: 'Already have an account?',
    dontAcc: 'Don’t have an account?',
    agreeWith: 'Agree with',
    termsAndC: 'Terms & Condition',
    privacyP: 'Privacy Policy',
    forgotPassword: 'Forgot Password?',
    forgotPasswordDes: 'Enter the email address associated with your account and we will send you the link to reset password.',
    rememberPassword: 'Remember Password?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    login: 'Login',
    submit: 'Submit',
    empCode: 'EMP Code',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    mobileNumber: 'Mobile Number',
    dateOfBirth: 'Date Of Birth',
    role: 'Role',
    status: 'Status',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullNameV1: 'Please enter your full name!',
    emailAddressV1: 'Please enter your email!',
    emailAddressV2: 'Invalid email format',
    mobileNumberV1: 'Please enter your mobile number',
    mobileNumberV2: 'Invalid mobile number format',
    passwordV1: 'Please enter your password!',
    passwordV2: 'Password must start with an uppercase letter.',
    passwordV3: 'Password must contain at least one number.',
    passwordV4: 'Password must contain at least one special character.',
    passwordV5: 'Password must be at least 8 characters long.',
    confirmPasswordV1: 'Please enter your confirm password!',
    confirmPasswordV2: 'Password do not matched!',
    hey: 'Hey',
    motiveLine: 'Have a productive and amazing day!',
    clockInOut: 'Clock In / Out',
    startTracking: 'Start Tracking',
    stopTracking: 'Stop Tracking',
    clockIn: 'Clock In',
    clockOut: 'Clock Out',
    breakIn: 'Break In',
    breakOut: 'Break Out',
    totalTime: 'Total Time',
    workingTime: 'Working Time',
    breakTime: 'Break Time',
    liveTracking: 'Live Tracking',
    todayActivity: 'Today Activity',
    earlyOutReminder: 'Early Out Reminder',
    attendanceReport: 'Attendance Report',
    leaveReport: 'Leave Report',
    noticeBoard: 'Notice Board',
    action: 'Action',
    delete: 'Delete',
    deleteConfirmation: 'Sure to delete?',
    approveConfirmation: 'Sure to Approve this user?',
    approve: 'Approve',
    rejectConfirmation: 'Sure to Reject this user?',
    edit: 'Edit',
    view: 'View',
    reject: 'Reject',
    empSearchHint: 'Search by name, email or mobile',
    searchHint: 'Search Record...',
    attReportSearchHint: 'Search by name',
    approvalStatus: 'Approval Status',
    isActive: 'Active',
    emergencyContactNo: 'Emergency Contact No',
    technology: 'Technology',
    gender: 'Gender',
    bloodGroup: 'Blood Group',
    skills: 'Skills',
    address: 'Address',
    pincode: 'Pincode',
    aadharNumber: 'Aadhar Number',
    panNumber: 'PAN Number',
    bankAccountNumber: 'Bank Account Number',
    ifscCode: 'IFSC Code',
    dateOfJoining: 'Date of Joining',
    dateOfLeaving: 'Date of Leaving',
    financialDetails: 'Financial Details',
    admin: 'Admin',
    employee: 'Employee',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    empStatus: 'Employee Status',
    personalDetails: 'Personal Details',
    profileDetails: 'Profile Details',
    active: 'Active',
    addRecord: 'Add Record',
    updateRecord: 'Update Record',
    addEmployee: 'Add Employee',
    updateEmployee: 'Update Employee',
    addBasicSalary: 'Add Basic Salary',
    updateBasicSalary: 'Update Basic Salary',
    addEvent: "Add Event",
    updateEvent: "Update Event",
    addLeave: "Add Leave",
    updateLeave: "Update Leave",
    addClient: 'Add Client',
    updateClient: 'Update Client',
    addProject: 'Add Project',
    updateProject: 'Update Project',
    profileUrl: 'Profile Url',
    profile: 'Profile',
    userName: 'User Name',
    totalHours: 'Total Hours',
    workingHours: 'Working Hours',
    breakHours: 'Break Hours',
    lateArrival: 'Late Arrival',
    overtime: 'Overtime',
    screenshots: 'Screenshots',
    eventCount: 'Event Count',
    userDetail: 'User Detail',
    todayReport: 'Today Report',
    attendanceDetail: 'Attendance Detail',
    punchInAt: 'Punch In At',
    user: 'User',
    basicSalary: 'Basic Salary',
    code: 'Code',
    startDate: 'Start Date',
    endDate: 'End Date',
    showAmount: 'Show Amount',
    hideAmount: 'Hide Amount',
    clientName: 'Client Name',
    createdAt: 'Created Date',
    projectName: 'Project Name',
    projectType: 'Project Type',
    projectStatus: 'Project Status',
    projectPriority: 'Project Priority',
    adminSetting: 'Admin Setting',
    officeTimeSetting: 'Office Time Settings',
    screenshotSettings: 'Screenshot Settings',
    leaveSettings: 'Leave Settings',
    monthlyTotalHours: 'Monthly Total Hours',
    appSetting: 'App Setting',
    dailyTime: 'Daily Time',
    officeUpdates: 'Office Updates',
    adminEmail: 'Admin Email',
    officeStartTime: 'Office Start Time',
    officeEndTime: 'Office End Time',
    breakDuration: 'Break Duration',
    screenshotTime: "SS Capture Time",
    isTakeScreenShot: "Is Take SS",
    showScreenShot: "Is Show SS To User",
    yearlyPaidLeave: "Yearly Paid Leave",
    monthlyMaxPaidLeave: "Monthly Max Paid Leave",
    hours: "Hours",
    save: "Save",
    insertYearlyData: "Insert Yearly Data",
    addOfficeEvent: "Add Office Event",
    title: "Title",
    description: "Description",
    showTime: "Event Show Time",
    isDaily: "Show Daily",
    isForDailyUpdate: "For Daily Report",
    windowLink: "Redirect Link",
    date: "Date",
    startTime: "Start Time",
    endTime: "End Time",
    breakAllow: "Break Allow",
    isLeaveOnDay: "Is Leave On Day",
    totalHour: "Total Hour",
    leaveType: "Leave Type",
    leaveHalfDayType: "Leave Halfday Type",
    leaveHours: "Leave Hours",
    dayType: "Day Type",
    leaveCategory: "Leave Category",
    leaveStatus: "Leave Status",
    reason: "Reason",
    rejectedReason: "Rejected Reason",
    isUnexpected: "Is Unexpected",
    sandwichLeave: "Sandwich Leave",
    changeStatus: "Change Status",
    selectUser: "Select User",
    unexpectedLeaves: "Unexpected Leaves",
    selectOne: "Select One",
    report: "Report",
    confirmation: "Confirmation!",
    logoutConfirmation: "Are you sure you want to log out?",
    logOut: "LogOut",
};

export default appString;