const extIcons = {
    doc: "/assets/fileExtIcons/doc.png",
    dat: "/assets/fileExtIcons/dat.png",
    bmp: "/assets/fileExtIcons/bmp.png",
    psd: "/assets/fileExtIcons/psd.png",
    wmv: "/assets/fileExtIcons/wmv.png",
    avi: "/assets/fileExtIcons/avi.png",
    indd: "/assets/fileExtIcons/indd.png",
    html: "/assets/fileExtIcons/html.png",
    cdr: "/assets/fileExtIcons/cdr.png",
    midi: "/assets/fileExtIcons/midi.png",
    gif: "/assets/fileExtIcons/gif.png",
    dll: "/assets/fileExtIcons/dll.png",
    php: "/assets/fileExtIcons/php.png",
    iso: "/assets/fileExtIcons/iso.png",
    eps: "/assets/fileExtIcons/eps.png",
    pdf: "/assets/fileExtIcons/pdf.png",
    css: "/assets/fileExtIcons/css.png",
    raw: "/assets/fileExtIcons/raw.png",
    zip: "/assets/fileExtIcons/zip.png",
    xml: "/assets/fileExtIcons/xml.png",
    i_3ds: "/assets/fileExtIcons/i_3ds.png",
    xls: "/assets/fileExtIcons/xls.png",
    mp3: "/assets/fileExtIcons/mp3.png",
    flv: "/assets/fileExtIcons/flv.png",
    aac: "/assets/fileExtIcons/aac.png",
    tif: "/assets/fileExtIcons/tif.png",
    fla: "/assets/fileExtIcons/fla.png",
    svg: "/assets/fileExtIcons/svg.png",
    dmg: "/assets/fileExtIcons/dmg.png",
    png: "/assets/fileExtIcons/png.png",
    ps: "/assets/fileExtIcons/ps.png",
    ppt: "/assets/fileExtIcons/ppt.png",
    mpg: "/assets/fileExtIcons/mpg.png",
    ai: "/assets/fileExtIcons/ai.png",
    file: "/assets/fileExtIcons/file.png",
    txt: "/assets/fileExtIcons/txt.png",
    js: "/assets/fileExtIcons/js.png",
    jpg: "/assets/fileExtIcons/jpg.png",
    cad: "/assets/fileExtIcons/cad.png",
    sql: "/assets/fileExtIcons/sql.png",
    mov: "/assets/fileExtIcons/mov.png",
};

export default extIcons;