const imagePaths = {
    ringtone: '/assets/ringtone.mp3',
    auth_design_bg: '/assets/images/auth_design_bg.svg',
    icon_big_dark: '/assets/images/icon_big_dark.png',
    icon_big_white: '/assets/images/icon_big_white.png',
    icon_sm_dark: '/assets/images/icon_sm_dark.png',
    icon_sm_white: '/assets/images/icon_sm_white.png',
    icon_sm_multi: '/assets/images/icon_sm_multi.png',
    right_tick: '/assets/images/right_tick.svg',
    auth_design_dot_square: '/assets/images/auth_design_dot_square.png',
    auth_design_round_big: '/assets/images/auth_design_round_big.png',
    auth_design_round_small: '/assets/images/auth_design_round_small.png',
    heyWaveHand: '/assets/images/heyWaveHand.png',
    male_profile: '/assets/images/male_profile.png',
    female_profile: '/assets/images/female_profile.png',
    priority_clear: '/assets/images/priority_clear.png',
    priority_high: '/assets/images/priority_high.png',
    priority_low: '/assets/images/priority_low.png',
    priority_normal: '/assets/images/priority_normal.png',
    priority_on_hold: '/assets/images/priority_on_hold.png',
    priority_urjent: '/assets/images/priority_urjent.png',
    chatIcon: '/assets/images/chatIcon.png',
    emojiHey: '/assets/images/emojiHey.png',
};

export default imagePaths;