const pageRoutes = {
    loginPage: '/login',
    signupPage: '/signup',
    forgotPasswordPage: '/forgot-password',
    dashboard: '/dashboard',
    tracker: '/tracker',
    employees: '/employees',
    employeeDetail: '/employee-detail',
    todayReport: '/today-report',
    basicSalary: '/basic-salary',
    client: '/client',
    project: '/project',
    tasks: '/tasks',
    dailyUpdate: '/daily-update',
    leave: '/leave',
    leaveReport: '/leave-report',
    salaryReport: '/salary-report',
    punchReport: '/punch-report',
    calendar: '/calendar',
    chatting: '/chatting',
    application: '/application',
    myProfile: '/my-profile',
    settings: '/settings',
    calling: '/dashboard',
    appUpdate: '/app-update',
};

export default pageRoutes;